name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Package
      uses: ConorMacBride/install-package@v1.1.0
      with:
        apt: git build-essential flex bison autoconf libtool libfreetype-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxcursor-dev libxinerama-dev libxrender-dev libxcomposite-dev

    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2    

    - name: configure
      # Windows 64-bit build config
      run: ./configure --host=x86_64-w64-mingw32 --with-wine-tools=../wine-tools --without-x --disable-tests --enable-win64
      # Windows 32-bit build config
      #run: ./configure --host=i686-w64-mingw32 --without-x --disable-tests
    - name: make
      run: make -j$(nproc)
