name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Package
      uses: ConorMacBride/install-package@v1.1.0
      with:
        apt: git build-essential flex bison autoconf pkgconf libtool libfreetype6-dev libfreetype-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxcursor-dev libxinerama-dev libxrender-dev libxcomposite-dev

    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2   

    - name: Make directories
      run: |
        mkdir mingw64-freetype
        mkdir wine-tools

    - name: Setup MinGW freetype
      working-directory: mingw64-freetype
      run: | 
        wget https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-freetype-2.13.3-1-any.pkg.tar.zst
        unzstd mingw-w64-x86_64-freetype-2.13.3-1-any.pkg.tar.zst
        rm mingw-w64-x86_64-freetype-2.13.3-1-any.pkg.tar.zst
        tar -xf mingw-w64-x86_64-freetype-2.13.3-1-any.pkg.tar
        rm mingw-w64-x86_64-freetype-2.13.3-1-any.pkg.tar

    - name: configure Wine Tools
      working-directory: wine-tools
      run: ../configure --disable-tests --without-x --enable-win64
    - name: make Wine Tools
      working-directory: wine-tools
      run: make -j$(nproc)

    - name: configure Windows build
      # Windows 64-bit build config
      run: ./configure --host=x86_64-w64-mingw32 --with-freetype-prefix=./mingw64-freetype/mingw64 --with-wine-tools=./wine-tools --without-x --disable-tests --enable-win64
      # Windows 32-bit build config
      #run: ./configure --host=i686-w64-mingw32 --without-x --disable-tests
      
    - name: make Wine for Windows x64
      run: make -j$(nproc)
